language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

script:
  - yarn build

deploy:
  provider: pages
  script:
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
